version: '3.8'
services:
  postgres:
    image: postgres:17.6
    container_name: gator_db
    environment:
      POSTGRES_DB: gator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: